#!/bin/sh

# cleanup

rm - rf obj_dir
rm -f lsfr4.vcd

# run Verilator to translate SystemVerilog into C++, including C++ testbench
verilator -Wall --cc --trace lsfr4.sv --exe lsfr4_tb.cpp

#build C++ project via make automattically generated by Verilator 
make -j -C obj_dir/ -f Vlsfr4.mk Vlsfr4

# run executable simulation file 
obj_dir/Vlsfr4